// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl1ru2UQCoGibjXcjVpa9-vQLblHsljGM',
    appId: '1:579563703186:web:869f6e4d599686817f8f4b',
    messagingSenderId: '579563703186',
    projectId: 'lojavirtual-pro',
    authDomain: 'lojavirtual-pro.firebaseapp.com',
    databaseURL: 'https://lojavirtual-pro-default-rtdb.firebaseio.com',
    storageBucket: 'lojavirtual-pro.appspot.com',
    measurementId: 'G-5L18QFB2MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ3_sCGzWCxREnYtEQhZq3rTLh4Otduxg',
    appId: '1:579563703186:android:7e39d675c97ee9d87f8f4b',
    messagingSenderId: '579563703186',
    projectId: 'lojavirtual-pro',
    databaseURL: 'https://lojavirtual-pro-default-rtdb.firebaseio.com',
    storageBucket: 'lojavirtual-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTIhgOL2IIYlBZDnc1-gVg72JsfwJxe2w',
    appId: '1:579563703186:ios:6bc1cf68c2ca91657f8f4b',
    messagingSenderId: '579563703186',
    projectId: 'lojavirtual-pro',
    databaseURL: 'https://lojavirtual-pro-default-rtdb.firebaseio.com',
    storageBucket: 'lojavirtual-pro.appspot.com',
    iosBundleId: 'br.com.arthurmariano.lojaVirtualPro',
  );
}
